spring:
  application:
    name: Store
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root
    password: 808959
stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enable: true
  supported-currencies: USD,EUR,GBP
payment:
  stripe: false
mail:
  host: http://smtp.gmail.com
  port: 5761